export const QUALITY_PRESETS = {
  high: {
    id: 'high',
    label: 'High',
    dpr: [1, 1.75],
    antialias: true,
    sparklesCount: 90,
    sparklesSize: 2,
    nodeResolution: 10,
    linkResolution: 8,
    cooldownTicks: 120,
    cooldownTime: 22000,
    chargeStrength: -185,
    chargeDistanceMax: 900,
    linkDistanceBase: 52,
    linkDistanceScale: 14,
    directionalParticlesIdle: 1,
    directionalParticlesHighlight: 3,
    hideInactive: false,
  },
  balanced: {
    id: 'balanced',
    label: 'Balanced',
    dpr: [1, 1.35],
    antialias: false,
    sparklesCount: 35,
    sparklesSize: 1.5,
    nodeResolution: 7,
    linkResolution: 5,
    cooldownTicks: 80,
    cooldownTime: 14000,
    chargeStrength: -155,
    chargeDistanceMax: 720,
    linkDistanceBase: 48,
    linkDistanceScale: 12,
    directionalParticlesIdle: 0,
    directionalParticlesHighlight: 2,
    hideInactive: false,
  },
  performance: {
    id: 'performance',
    label: 'Performance',
    dpr: [1, 1],
    antialias: false,
    sparklesCount: 0,
    sparklesSize: 1,
    nodeResolution: 5,
    linkResolution: 3,
    cooldownTicks: 45,
    cooldownTime: 6500,
    chargeStrength: -130,
    chargeDistanceMax: 560,
    linkDistanceBase: 44,
    linkDistanceScale: 10,
    directionalParticlesIdle: 0,
    directionalParticlesHighlight: 1,
    hideInactive: true,
  },
}

export const DEFAULT_QUALITY_MODE = 'balanced'
